import type { ServicePage, SolutionHub, SolutionSlug } from "./types";

const UPDATED = "2026-09-24";

export const hubs: SolutionHub[] = [
  {
    slug: "atendimento-inteligente",
    name: "Atendimento Inteligente",
    shortName: "Atendimento",
    menuDescription: "Resposta em segundos, 24/7, com transbordo para humano quando preciso.",
    icon: "message",
    title: "Atendimento com IA 24/7 para Empresas",
    metaDescription:
      "Agentes de IA que atendem seus clientes 24/7 no WhatsApp, no site e em todos os canais, com transbordo para humano. Diagnóstico com ROI. Atendemos todo o Brasil.",
    h1: "Atendimento que nunca dorme, e nunca deixa um cliente esperando.",
    answer:
      "Implantamos agentes de IA que atendem seus clientes 24/7 no WhatsApp, no site e em todos os canais, respondendo dúvidas, agendando e transferindo para um humano quando necessário. Reduzem o tempo de resposta a segundos e liberam sua equipe para o que exige gente de verdade.",
    problem: {
      title: "Cada mensagem sem resposta é um cliente indo para o concorrente.",
      items: [
        "Mensagens que chegam à noite e no fim de semana só são vistas no dia seguinte.",
        "A recepção responde as mesmas perguntas o dia inteiro.",
        "Quem espera muito por uma resposta já está conversando com outra empresa.",
        "Sem histórico organizado, cada atendente recomeça a conversa do zero.",
      ],
    },
    highlight: {
      eyebrow: "Transbordo inteligente",
      title: "Como o agente decide quando chamar um humano",
      text: "O transbordo não é improviso: é uma regra que definimos com você. Em todos os casos, a pessoa da equipe recebe o contexto completo — quem é o cliente, o que perguntou e o que já foi respondido.",
      points: [
        { title: "Pedido explícito", text: "O cliente pede para falar com uma pessoa e é atendido, sem labirinto de menus." },
        { title: "Tema sensível", text: "Reclamações, negociação e casos clínicos ou jurídicos vão direto para a equipe." },
        { title: "Baixa confiança", text: "Se o agente não tem certeza da resposta, ele não inventa: transfere." },
        { title: "Oportunidade quente", text: "Lead qualificado segue para o vendedor com o resumo da conversa." },
      ],
    },
    services: ["agente-ia-whatsapp", "agendamento-inteligente", "central-multicanal", "assistente-ia-para-site"],
    integrations: ["WhatsApp API oficial", "Instagram Direct", "Google Agenda", "RD Station", "HubSpot", "Pipedrive", "Sistemas de agendamento", "Planilhas", "ERPs via API"],
    faq: [
      { q: "O cliente percebe que está falando com uma IA?", a: "Recomendamos deixar claro que é um assistente virtual. A conversa é natural, em linguagem comum, e o cliente pode pedir um humano a qualquer momento." },
      { q: "Qual canal devo automatizar primeiro?", a: "Quase sempre o WhatsApp, porque concentra o maior volume. Confirmamos isso com os seus dados no Diagnóstico." },
      { q: "A IA pode responder algo errado?", a: "O agente responde com base no conhecimento da sua empresa e é configurado para transferir quando não tem certeza. Testamos com cenários reais antes de ir ao ar." },
      { q: "Quanto custa um agente de atendimento?", a: "O Agente de IA para WhatsApp parte de R$ 7.500 de implantação, com sustentação mensal. O preço fechado sai do Diagnóstico." },
    ],
    cta: { title: "Quantos clientes você perde fora do horário?", text: "No Diagnóstico medimos o seu volume, o tempo de resposta atual e o retorno de um agente." },
    guide: "ia-no-whatsapp",
  },
  {
    slug: "vendas-e-receita",
    name: "Vendas & Receita",
    shortName: "Vendas",
    menuDescription: "Leads qualificados, pipeline organizado e base reativada, sem esforço manual.",
    icon: "target",
    title: "Vendas com IA para Empresas",
    metaDescription:
      "IA que responde leads em segundos, qualifica, agenda reuniões, organiza o pipeline e reativa clientes parados. Mais vendas com a mesma equipe. Atendemos todo o Brasil.",
    h1: "Mais vendas com a mesma equipe.",
    answer:
      "Colocamos a IA para responder leads em segundos, qualificar, agendar reuniões, organizar o pipeline e reativar clientes parados. Sua equipe recebe só o que está pronto para fechar, e nenhum lead esfria por falta de follow-up.",
    problem: {
      title: "O lead não esfria por falta de interesse. Esfria por falta de resposta.",
      items: [
        "Leads de anúncio respondidos horas depois, quando já falaram com o concorrente.",
        "Vendedores gastando a manhã com contatos sem perfil.",
        "Orçamentos enviados e nunca acompanhados.",
        "Uma base de clientes antigos que ninguém volta a procurar.",
      ],
    },
    highlight: {
      eyebrow: "Máquina de Receita",
      title: "Do primeiro contato ao fechamento, sem buracos",
      text: "SDR com IA, CRM e funis automatizados funcionam melhor juntos. No pacote Máquina de Receita, cada lead é respondido, qualificado, registrado e acompanhado até a decisão.",
      points: [
        { title: "Responde em segundos", text: "O SDR com IA aborda o lead no canal em que ele chegou, a qualquer hora." },
        { title: "Qualifica e pontua", text: "Perguntas naturais separam quem tem perfil de quem ainda está pesquisando." },
        { title: "Agenda e registra", text: "Reunião marcada na agenda do vendedor e tudo registrado no CRM." },
        { title: "Nutre até o momento certo", text: "Quem não está pronto recebe acompanhamento automático, sem esquecimento." },
      ],
    },
    services: ["sdr-com-ia", "crm-e-pipeline", "funis-automatizados", "reativacao-de-clientes"],
    integrations: ["RD Station", "HubSpot", "Pipedrive", "Kommo", "WhatsApp API oficial", "Formulários e landing pages", "Meta Ads", "Google Ads", "E-mail marketing"],
    faq: [
      { q: "Por onde começar em vendas?", a: "Se você tem base de clientes parada, a Reativação costuma dar o retorno mais rápido. Se gera leads novos todo mês, o SDR com IA. O Diagnóstico mostra qual tem maior ROI no seu caso." },
      { q: "A IA substitui o time comercial?", a: "Não. A IA assume a pré-venda e o follow-up; quem negocia e fecha é o seu vendedor, agora com leads mais quentes." },
      { q: "Preciso ter um CRM?", a: "Ajuda muito. Se você ainda não tem, implantamos um como parte do projeto." },
      { q: "Quanto custa?", a: "SDR com IA a partir de R$ 15.000, CRM a partir de R$ 5.000, funis a partir de R$ 4.000 e reativação a partir de R$ 4.500 por campanha." },
    ],
    cta: { title: "Descubra quantos leads você perde hoje.", text: "No Diagnóstico medimos o tempo de resposta, a taxa de conversão e o potencial da sua base." },
    guide: "agentes-de-ia-para-empresas",
  },
  {
    slug: "operacoes",
    name: "Operações & Processos",
    shortName: "Operações",
    menuDescription: "Documentos, relatórios e integrações rodando sozinhos.",
    icon: "workflow",
    title: "Automação de Processos com IA para Empresas",
    metaDescription:
      "Automatizamos leitura de documentos, relatórios, integrações entre sistemas e tarefas repetitivas com agentes de IA. Menos digitação, menos erro. Atendemos todo o Brasil.",
    h1: "Sua equipe para de fazer trabalho de robô.",
    answer:
      "Automatizamos os processos que consomem horas da sua equipe: leitura e extração de documentos, geração de relatórios, integração entre sistemas e tarefas repetitivas. Agentes e fluxos assumem o operacional, com precisão e sem cansaço, e as pessoas voltam a fazer o que exige julgamento.",
    problem: {
      title: "Horas qualificadas gastas em tarefas que não exigem julgamento.",
      items: [
        "Dados copiados à mão do PDF para a planilha, e da planilha para o sistema.",
        "Relatórios montados toda semana, do mesmo jeito, por alguém caro.",
        "Sistemas que não conversam entre si.",
        "Processos que dependem da memória de uma pessoa.",
      ],
    },
    highlight: {
      eyebrow: "Automação com controle",
      title: "O padrão roda sozinho. A exceção vai para uma pessoa.",
      text: "Automação séria não é jogar tudo para a IA e torcer. Cada fluxo tem regras de validação, registro do que foi feito e uma fila de exceções com o motivo de cada caso.",
      points: [
        { title: "Validação", text: "Cada dado é conferido contra as suas regras de negócio antes de ser lançado." },
        { title: "Fila de exceções", text: "Só o que foge ao padrão chega à equipe, já com o motivo." },
        { title: "Rastreabilidade", text: "Logs de cada execução: o que entrou, o que saiu e quem aprovou." },
        { title: "Alertas", text: "Falhou uma integração? Você sabe na hora, e o reprocessamento é automático." },
      ],
    },
    services: ["automacao-de-documentos", "agente-de-conhecimento", "integracao-de-sistemas", "automacao-de-processos"],
    integrations: ["n8n", "Google Drive", "E-mail", "ERPs (Omie, Bling, TOTVS)", "Sistemas contábeis", "Sistemas jurídicos", "Planilhas", "Assinatura digital", "APIs e bancos de dados"],
    faq: [
      { q: "Qual processo automatizar primeiro?", a: "O que combina alto volume, regras claras e custo de erro. No Diagnóstico listamos os candidatos e o retorno estimado de cada um." },
      { q: "Automação com IA é confiável?", a: "É, quando tem validação, logs e fila de exceções. Nenhum dado incerto é lançado sem revisão." },
      { q: "Vocês usam n8n?", a: "Sim, quando faz sentido. Para casos específicos escrevemos código. Em ambos os casos, as contas e os fluxos ficam em nome da sua empresa." },
      { q: "Quanto custa?", a: "Automações intermediárias partem de R$ 4.000; automação de documentos de R$ 12.000; agentes operacionais de R$ 10.000." },
    ],
    cta: { title: "Quantas horas sua equipe gasta com trabalho repetitivo?", text: "No Diagnóstico mapeamos os processos e mostramos quanto tempo e dinheiro cada automação devolve." },
    guide: "agentes-de-ia-para-empresas",
  },
  {
    slug: "ia-corporativa",
    name: "IA Corporativa Privada",
    shortName: "IA Corporativa",
    menuDescription: "Inteligência com controle total dos dados, LGPD e governança.",
    icon: "lock",
    title: "IA Privada e Governança de IA para Empresas",
    metaDescription:
      "IA em ambiente privado, sem que os dados saiam do seu controle, com governança, controle de acesso e LGPD. Para jurídico, saúde e diretorias exigentes.",
    h1: "IA com segurança de nível empresarial.",
    answer:
      "Para empresas que lidam com dados sensíveis, implantamos IA em ambiente privado — sem que as informações saiam do seu controle — com governança, controle de acesso e adequação à LGPD. É a forma de usar IA com a segurança que jurídico, saúde e diretorias exigem.",
    problem: {
      title: "Sua equipe já usa IA. A questão é com quais dados.",
      items: [
        "Colaboradores colando contratos e dados de clientes em ferramentas públicas.",
        "Nenhuma política dizendo o que pode e o que não pode.",
        "Diretoria travando projetos de IA por medo de vazamento.",
        "Setores regulados sem saber como provar conformidade.",
      ],
    },
    highlight: {
      eyebrow: "Controle total",
      title: "Toda a inteligência, nenhum dado fora do lugar",
      text: "A IA corporativa combina tecnologia e regra: um ambiente onde os dados não treinam modelos de terceiros, e uma governança que diz quem usa, para quê e com qual registro.",
      points: [
        { title: "Não retenção", text: "Provedores com contrato de não retenção, ou modelo rodando em infraestrutura dedicada." },
        { title: "Controle de acesso", text: "Cada pessoa acessa só o que o perfil dela permite." },
        { title: "Logs e auditoria", text: "Registro de uso para demonstrar conformidade quando for preciso." },
        { title: "Política de uso", text: "Regras claras para a equipe, aprovadas pela diretoria." },
      ],
    },
    services: ["ia-privada", "governanca-ia-lgpd"],
    integrations: ["Microsoft Azure", "Google Cloud", "AWS", "Modelos abertos (on-premise)", "Google Drive", "SharePoint", "Sistemas jurídicos", "Prontuários eletrônicos"],
    note: "IA Preditiva (previsão de demanda, cancelamento e inadimplência) é oferecida sob consulta, somente após um diagnóstico de dados: ela depende de histórico organizado.",
    faq: [
      { q: "IA privada é só para empresas grandes?", a: "Não. A IA em nuvem privada atende escritórios e clínicas de porte médio com custo acessível. A infraestrutura dedicada é para exigências máximas." },
      { q: "Qual a diferença entre IA privada e governança?", a: "IA privada é o ambiente técnico onde os dados ficam protegidos. Governança são as regras, os controles e os registros de uso. O ideal é ter os dois." },
      { q: "Isso atende à LGPD?", a: "Sim, com base legal definida, controle de acesso, registros de uso e contratos adequados com os provedores." },
      { q: "E a IA Preditiva?", a: "Oferecemos sob consulta, depois de avaliar se a sua base de dados tem histórico suficiente. Não vendemos previsão sem dado." },
    ],
    cta: { title: "Quer usar IA sem abrir mão da confidencialidade?", text: "No Diagnóstico avaliamos a sensibilidade dos seus dados e o caminho mais adequado." },
    guide: "ia-e-lgpd",
  },
];

export const services: ServicePage[] = [
  // ───────────────────────── Atendimento Inteligente ─────────────────────────
  {
    slug: "agente-ia-whatsapp",
    solution: "atendimento-inteligente",
    name: "Agente de IA para WhatsApp",
    cardDescription: "Atende, tira dúvidas, agenda e vende no WhatsApp, 24/7, com transbordo para humano.",
    icon: "message",
    featured: true,
    title: "Agente de IA para WhatsApp para Empresas",
    metaDescription:
      "Agente de IA que atende, tira dúvidas, agenda e vende no WhatsApp 24/7, integrado ao seu CRM. API oficial e dados seguros. Implantação a partir de R$ 7.500.",
    h1: "Agente de IA para WhatsApp: atende, qualifica e agenda 24/7",
    answer:
      "Um agente de IA para WhatsApp é um atendente virtual que conversa com seus clientes em linguagem natural, responde dúvidas com base no conhecimento da sua empresa, agenda e vende, e passa para um humano quando o caso pede. Funciona 24 horas por dia, usa a API oficial do WhatsApp e se integra ao seu CRM e à sua agenda. Ideal para empresas que recebem muitas mensagens e perdem vendas fora do horário comercial.",
    forWho: [
      "Empresas que vendem ou agendam pelo WhatsApp e não conseguem responder a todos a tempo.",
      "Negócios que perdem contatos fora do horário comercial.",
      "Equipes pequenas afogadas em perguntas repetitivas.",
      "Clínicas, escritórios, imobiliárias, e-commerces e prestadores de serviço.",
    ],
    steps: [
      { title: "Treinamos o agente", text: "Com o conhecimento real do seu negócio: serviços, preços, regras e perguntas frequentes." },
      { title: "Conectamos", text: "À API oficial do WhatsApp, ao seu CRM e à sua agenda." },
      { title: "O cliente chama", text: "E o agente responde em segundos, a qualquer hora." },
      { title: "O agente age", text: "Tira dúvidas, agenda, envia documentos e qualifica o lead." },
      { title: "Transbordo inteligente", text: "Quando o caso exige, transfere para um humano com todo o contexto." },
    ],
    included: [
      "Agente treinado na base de conhecimento da empresa",
      "Integração com a API oficial do WhatsApp (conta em nome do cliente)",
      "Integração com CRM e agenda",
      "Regras de transbordo para atendimento humano",
      "Painel de conversas e acompanhamento",
      "Testes com cenários reais antes de ir ao ar",
      "Sustentação mensal (monitoramento, ajustes de prompt, atualização da base)",
    ],
    integrations: ["WhatsApp API oficial", "RD Station", "HubSpot", "Pipedrive", "Google Agenda", "Sistemas de agendamento", "Planilhas", "ERPs via integração sob medida"],
    pricing: {
      from: 7500,
      prefix: "Implantação a partir de",
      timeline: "2 a 3 semanas",
      details: [
        "Inclui plano de sustentação mensal.",
        "O consumo da API do WhatsApp é pago pela empresa, direto à Meta — o número e os dados são seus.",
      ],
    },
    security: "API oficial (sem risco de banimento), conta e dados em nome da sua empresa e adequação à LGPD.",
    indicators: [
      "Tempo até a primeira resposta",
      "% de conversas resolvidas sem intervenção humana",
      "Agendamentos e vendas originados pelo agente",
      "Conversas atendidas fora do horário comercial",
    ],
    demoCase: "agendamento-clinica-odontologica",
    faq: [
      { q: "Vou perder o controle do atendimento?", a: "Não. Você define quando o agente atua e quando transfere para um humano, e acompanha tudo pelo painel." },
      { q: "Funciona com o meu número atual?", a: "Sim, migramos para a API oficial mantendo seu número." },
      { q: "É seguro? E a LGPD?", a: "A conta e os dados ficam em nome da sua empresa, e seguimos as exigências da LGPD." },
      { q: "Quanto tempo para colocar no ar?", a: "De 2 a 3 semanas, dependendo das integrações." },
      { q: "E se eu quiser encerrar?", a: "Você mantém o número, os dados e o histórico; a saída está prevista em contrato." },
      { q: "Qual o custo das mensagens?", a: "A Meta cobra por mensagem, pago diretamente pela sua empresa; mostramos a estimativa no Diagnóstico." },
    ],
    cta: { title: "Quer ver seu agente funcionando?", text: "Comece pelo Diagnóstico." },
    related: ["agendamento-inteligente", "sdr-com-ia"],
    guide: "ia-no-whatsapp",
    visual: "whatsapp",
    updatedAt: UPDATED,
  },
  {
    slug: "agendamento-inteligente",
    solution: "atendimento-inteligente",
    name: "Agendamento Inteligente",
    cardDescription: "Agenda cheia e menos faltas: o agente marca, confirma e remarca sozinho.",
    icon: "calendar",
    title: "Agendamento Inteligente com IA para Empresas",
    metaDescription:
      "Agente de IA que agenda, confirma e remarca horários pelo WhatsApp 24/7, integrado à sua agenda. Menos faltas, recepção livre. Módulo a partir de R$ 3.500.",
    h1: "Agendamento Inteligente: agenda cheia, menos faltas e recepção livre",
    answer:
      "O Agendamento Inteligente é um agente de IA que marca, confirma e remarca horários pelo WhatsApp, consultando a sua agenda em tempo real. Envia lembretes, oferece encaixes quando alguém desmarca e reduz as faltas. Ideal para clínicas, consultórios e prestadores de serviço que vivem de agenda.",
    forWho: [
      "Clínicas e consultórios com faltas frequentes.",
      "Recepções que passam o dia confirmando horários por telefone.",
      "Negócios que perdem agendamentos à noite e no fim de semana.",
      "Empresas com vários profissionais, salas ou unidades.",
    ],
    steps: [
      { title: "Conectamos a sua agenda", text: "Google Agenda ou sistema de agendamento, com regras de horários, profissionais e durações." },
      { title: "O cliente pede um horário", text: "Pelo WhatsApp, a qualquer hora, em linguagem natural." },
      { title: "O agente oferece opções reais", text: "Consulta a disponibilidade e confirma direto na agenda." },
      { title: "Lembretes automáticos", text: "Confirmação de presença antes do horário, sem ligação da recepção." },
      { title: "Remarcação e encaixe", text: "Desmarcou? O agente remarca e oferece a vaga para a lista de espera." },
    ],
    included: [
      "Integração com a agenda (Google Agenda ou sistema de agendamento)",
      "Regras por profissional, serviço, duração e unidade",
      "Confirmação e lembretes automáticos",
      "Remarcação e lista de espera",
      "Transbordo para a recepção em casos específicos",
      "Relatório de ocupação e faltas",
      "Sustentação mensal",
    ],
    integrations: ["Google Agenda", "Sistemas de agendamento com API", "Sistemas clínicos", "WhatsApp API oficial", "Planilhas"],
    pricing: {
      from: 3500,
      prefix: "Módulo a partir de",
      timeline: "1 a 2 semanas",
      details: [
        "Incluso no plano Profissional do Agente de IA para WhatsApp.",
        "Inclui sustentação mensal.",
        "Mensagens da API do WhatsApp pagas pela empresa, direto à Meta.",
      ],
    },
    security: "Dados de agenda e de clientes ficam nos seus sistemas, com acesso restrito e adequação à LGPD — inclusive para dados de saúde.",
    indicators: ["Taxa de faltas (no-show)", "Ocupação da agenda", "Agendamentos feitos fora do horário comercial", "Horas de recepção liberadas"],
    demoCase: "agendamento-clinica-odontologica",
    faq: [
      { q: "Funciona com o sistema de agendamento que eu já uso?", a: "Se o sistema tem API ou integração, conectamos direto. Se não tem, usamos o Google Agenda como ponte. Avaliamos no Diagnóstico." },
      { q: "O agente lida com vários profissionais e unidades?", a: "Sim. Cada profissional, serviço e unidade tem suas próprias regras de horário e duração." },
      { q: "E se o paciente quiser falar com a recepção?", a: "O agente transfere a conversa com o contexto completo, e a recepção continua de onde parou." },
      { q: "Os lembretes reduzem faltas de verdade?", a: "Lembretes com confirmação ativa são uma das formas mais simples de reduzir faltas. Medimos a sua taxa antes e depois para você ver o efeito real." },
      { q: "Quanto tempo para implantar?", a: "De 1 a 2 semanas como módulo; junto com o agente de WhatsApp, entra no mesmo cronograma." },
    ],
    cta: { title: "Quantos horários ficam vazios por semana na sua agenda?", text: "Comece pelo Diagnóstico." },
    related: ["agente-ia-whatsapp", "central-multicanal"],
    guide: "ia-no-whatsapp",
    visual: "calendar",
    updatedAt: UPDATED,
  },
  {
    slug: "central-multicanal",
    solution: "atendimento-inteligente",
    name: "Central Multicanal",
    cardDescription: "WhatsApp, Instagram, site e e-mail em uma caixa única, com IA na linha de frente.",
    icon: "inbox",
    title: "Central de Atendimento Multicanal com IA para Empresas",
    metaDescription:
      "WhatsApp, Instagram, site e e-mail em uma caixa de entrada única, com IA respondendo e distribuindo conversas. Nenhuma mensagem perdida. A partir de R$ 6.000.",
    h1: "Central Multicanal: todos os canais em uma caixa só, com IA na linha de frente",
    answer:
      "A Central Multicanal reúne WhatsApp, Instagram, chat do site e e-mail em uma única caixa de entrada, com um agente de IA respondendo primeiro e distribuindo cada conversa para a pessoa certa. Nenhuma mensagem se perde entre canais, e a equipe atende com o histórico completo do cliente. Ideal para empresas com atendimento intenso em vários canais.",
    forWho: [
      "Empresas que atendem por WhatsApp, Instagram, site e e-mail ao mesmo tempo.",
      "Equipes que perdem mensagens porque cada canal fica em um lugar.",
      "Gestores sem visão de volume, tempo de resposta e gargalos.",
      "Operações com vários atendentes ou setores.",
    ],
    steps: [
      { title: "Mapeamos canais e filas", text: "Quem atende o quê, em que horário e com qual prioridade." },
      { title: "Unificamos a caixa de entrada", text: "Todos os canais chegam a um só lugar, com histórico por cliente." },
      { title: "A IA responde primeiro", text: "Em qualquer canal, em segundos, com a mesma base de conhecimento." },
      { title: "Distribuição automática", text: "Cada conversa vai para o setor ou o atendente certo." },
      { title: "Painel de gestão", text: "Volume, tempo de resposta e gargalos à vista, por canal e por pessoa." },
    ],
    included: [
      "Caixa de entrada unificada (WhatsApp, Instagram, site, e-mail)",
      "Agente de IA treinado na base da empresa",
      "Regras de distribuição por setor e horário",
      "Histórico unificado por cliente",
      "Painel de métricas de atendimento",
      "Treinamento da equipe",
      "Sustentação mensal",
    ],
    integrations: ["WhatsApp API oficial", "Instagram Direct", "Chat do site", "E-mail", "RD Station", "HubSpot", "Pipedrive"],
    pricing: {
      from: 6000,
      prefix: "Implantação a partir de",
      timeline: "3 a 4 semanas",
      details: [
        "Inclui sustentação mensal.",
        "Licenças de plataformas de terceiros, quando necessárias, são pagas pela empresa.",
      ],
    },
    security: "Permissões por setor e atendente, histórico em contas da sua empresa e adequação à LGPD.",
    indicators: ["Tempo de primeira resposta por canal", "Conversas resolvidas pela IA", "Mensagens sem resposta", "Volume por canal e por atendente"],
    faq: [
      { q: "Preciso trocar a ferramenta de atendimento que já uso?", a: "Não necessariamente. Se a sua ferramenta permitir, integramos a IA a ela; se não, implantamos uma plataforma adequada." },
      { q: "A licença da plataforma está inclusa?", a: "Licenças de terceiros são pagas pela empresa, com transparência. Estimamos o custo no Diagnóstico." },
      { q: "Funciona com o Instagram?", a: "Sim, pela integração oficial do Instagram Direct." },
      { q: "Cada atendente vê só o seu setor?", a: "Sim, com permissões por setor e por fila." },
    ],
    cta: { title: "Quantas mensagens se perdem entre os seus canais?", text: "Comece pelo Diagnóstico." },
    related: ["agente-ia-whatsapp", "assistente-ia-para-site"],
    guide: "agentes-de-ia-para-empresas",
    visual: "inbox",
    updatedAt: UPDATED,
  },
  {
    slug: "assistente-ia-para-site",
    solution: "atendimento-inteligente",
    name: "Assistente de IA para Site",
    cardDescription: "Chat no seu site que responde, qualifica e converte visitantes em contatos.",
    icon: "globe",
    title: "Assistente de IA para Site para Empresas",
    metaDescription:
      "Chat com IA no seu site, treinado na base de conhecimento da empresa, que tira dúvidas e converte visitantes em leads 24/7. A partir de R$ 3.500.",
    h1: "Assistente de IA para Site: o visitante pergunta, a empresa responde na hora",
    answer:
      "O Assistente de IA para Site é um chat treinado na base de conhecimento da sua empresa que responde às dúvidas dos visitantes em linguagem natural, 24/7, e transforma interesse em contato: coleta dados, agenda ou leva para o WhatsApp. Ideal para sites com tráfego que não converte e empresas que querem atender sem formulário.",
    forWho: [
      "Sites com visitas, mas poucos contatos.",
      "Empresas cujos serviços geram muitas dúvidas antes da compra.",
      "Quem já tem o agente de WhatsApp e quer o mesmo conhecimento no site.",
      "Quem investe em SEO e anúncios e quer converter melhor esse tráfego.",
    ],
    steps: [
      { title: "Treinamos o assistente", text: "Com o conteúdo do site, serviços, preços e perguntas frequentes." },
      { title: "Instalamos no seu site", text: "Com a identidade visual da marca, sem refazer nada." },
      { title: "O visitante pergunta", text: "E recebe resposta na hora, em linguagem natural." },
      { title: "Captura do contato", text: "O assistente coleta os dados e registra no CRM." },
      { title: "Próximo passo", text: "Casos específicos seguem para o WhatsApp ou para a equipe." },
    ],
    included: [
      "Base de conhecimento da empresa",
      "Widget de chat com a identidade da marca",
      "Captura de leads com registro no CRM",
      "Transbordo para WhatsApp ou equipe",
      "Painel de conversas",
      "Sustentação mensal",
    ],
    integrations: ["WordPress", "Next.js", "Webflow", "Qualquer site (trecho de código)", "RD Station", "HubSpot", "WhatsApp API oficial", "Google Analytics"],
    pricing: {
      from: 3500,
      prefix: "Implantação a partir de",
      timeline: "1 a 2 semanas",
      details: [
        "R$ 1.500 se você já tem o nosso Agente de IA para WhatsApp (mesma base de conhecimento).",
        "Inclui sustentação mensal.",
      ],
    },
    security: "O assistente responde apenas com a base aprovada por você; dados de contato vão para o seu CRM, com consentimento e adequação à LGPD.",
    indicators: ["Conversas iniciadas por visitantes", "Leads capturados pelo assistente", "Taxa de conversão do site", "Perguntas mais frequentes (que viram conteúdo)"],
    faq: [
      { q: "Funciona no meu site atual?", a: "Sim. Instalamos em qualquer site com um trecho de código; não é preciso refazer o site." },
      { q: "O assistente pode inventar respostas?", a: "Ele responde com base na sua base de conhecimento e é configurado para não inventar: quando não sabe, oferece contato humano." },
      { q: "Posso usar o mesmo conhecimento do agente de WhatsApp?", a: "Sim, e é o recomendado: uma base só, respostas consistentes em todos os canais." },
      { q: "Deixa o site mais lento?", a: "Não. O chat carrega depois da página, sem afetar o carregamento." },
    ],
    cta: { title: "Seu site recebe visitas e não gera contatos?", text: "Comece pelo Diagnóstico." },
    related: ["agente-ia-whatsapp", "central-multicanal"],
    guide: "geo-como-aparecer-nas-ias",
    visual: "sitechat",
    updatedAt: UPDATED,
  },

  // ───────────────────────── Vendas & Receita ─────────────────────────
  {
    slug: "sdr-com-ia",
    solution: "vendas-e-receita",
    name: "SDR com IA",
    cardDescription: "Aborda cada lead em segundos, qualifica e agenda reunião com o seu vendedor.",
    icon: "target",
    featured: true,
    title: "SDR com IA para Empresas",
    metaDescription:
      "Um SDR com IA responde cada lead em segundos, qualifica e agenda reunião com seu vendedor, 24/7. Integrado ao CRM. Implantação a partir de R$ 15.000.",
    h1: "SDR com IA: responde, qualifica e agenda antes do concorrente",
    answer:
      "Um SDR com IA é um agente de pré-vendas que aborda cada lead em segundos, faz as perguntas de qualificação, identifica quem tem perfil e fit, e agenda a reunião direto na agenda do vendedor. Trabalha 24/7, registra tudo no CRM e garante que nenhum lead fique sem resposta. Ideal para empresas que investem em geração de leads e perdem oportunidades por demora no primeiro contato.",
    forWho: [
      "Empresas que geram leads (anúncios, indicações, portais) e demoram a responder.",
      "Times comerciais que perdem tempo com leads sem perfil.",
      "Negócios que querem escalar vendas sem inchar a equipe.",
    ],
    steps: [
      { title: "Definimos o perfil de lead ideal", text: "E o roteiro de qualificação, junto com você." },
      { title: "O lead chega", text: "Pelo site, anúncio ou WhatsApp, e o SDR aborda na hora." },
      { title: "Qualifica", text: "Com perguntas naturais, e pontua o lead." },
      { title: "Agenda", text: "A reunião com o vendedor certo, e registra tudo no CRM." },
      { title: "Nutre", text: "Quem ainda não está pronto, até o momento certo." },
    ],
    included: [
      "Roteiro de qualificação",
      "Integração com CRM e agenda",
      "Pontuação de leads",
      "Agendamento automático",
      "Sequências de nutrição",
      "Sustentação mensal",
    ],
    integrations: ["RD Station", "HubSpot", "Pipedrive", "Kommo", "WhatsApp API oficial", "Formulários e landing pages", "Meta Ads", "Google Ads"],
    pricing: {
      from: 15000,
      prefix: "Implantação a partir de",
      timeline: "3 a 5 semanas",
      details: [
        "Inclui sustentação mensal.",
        "Combina com CRM e Funis no pacote Máquina de Receita.",
      ],
    },
    security: "Dados no CRM da sua empresa, conformidade com a LGPD e consentimento nas abordagens ativas.",
    indicators: ["Leads qualificados por mês", "Tempo até a primeira resposta", "% de reuniões que viram proposta", "Leads sem resposta (a meta é zero)"],
    demoCase: "sdr-juridico-trabalhista",
    faq: [
      { q: "O SDR com IA substitui meu vendedor?", a: "Não. Ele faz a pré-venda e entrega o lead quente; quem fecha é o seu vendedor." },
      { q: "Ele conversa de forma natural?", a: "Sim, entende contexto e responde em linguagem natural. Não é um menu de opções." },
      { q: "Integra com o meu CRM?", a: "Integramos com os principais CRMs do mercado." },
      { q: "Posso usar em campanhas ativas?", a: "Sim, respeitando o consentimento e as regras do WhatsApp e da LGPD." },
    ],
    cta: { title: "Descubra quantos leads você perde hoje.", text: "Comece pelo Diagnóstico." },
    related: ["crm-e-pipeline", "funis-automatizados"],
    guide: "agentes-de-ia-para-empresas",
    visual: "leadscore",
    updatedAt: UPDATED,
  },
  {
    slug: "crm-e-pipeline",
    solution: "vendas-e-receita",
    name: "CRM & Pipeline Inteligente",
    cardDescription: "CRM com etapas automáticas, pontuação de leads e alertas de follow-up.",
    icon: "kanban",
    title: "CRM e Pipeline Inteligente para Empresas",
    metaDescription:
      "Implantação de CRM com etapas automáticas, pontuação de leads e alertas de follow-up, integrado ao WhatsApp e ao site. A partir de R$ 5.000.",
    h1: "CRM & Pipeline Inteligente: cada oportunidade no lugar certo, na hora certa",
    answer:
      "Implantamos e automatizamos o seu CRM para que cada lead entre sozinho, avance de etapa com base no que acontece e gere alertas quando alguém precisa agir. A pontuação automática mostra quem está pronto para comprar. Ideal para empresas que vendem por WhatsApp e planilha e perdem oportunidades por falta de acompanhamento.",
    forWho: [
      "Empresas que controlam vendas em planilha ou na memória do vendedor.",
      "Times com CRM contratado e pouco usado.",
      "Gestores sem previsão de receita confiável.",
      "Negócios com orçamentos enviados e nunca acompanhados.",
    ],
    steps: [
      { title: "Desenhamos o funil", text: "Etapas, critérios de avanço e responsáveis, junto com você." },
      { title: "Implantamos o CRM", text: "Ou organizamos o que você já tem." },
      { title: "Conectamos as entradas", text: "Site, WhatsApp, anúncios e formulários entram sozinhos." },
      { title: "Automatizamos o acompanhamento", text: "Etapas, tarefas e alertas de follow-up sem depender de memória." },
      { title: "Pontuação e previsão", text: "Quem está pronto para comprar, e quanto deve entrar no mês." },
    ],
    included: [
      "Desenho do funil de vendas",
      "Implantação ou reorganização do CRM",
      "Integração das entradas de leads",
      "Automações de etapa, tarefa e alerta",
      "Pontuação de leads",
      "Painel de vendas e previsão",
      "Treinamento da equipe",
      "Sustentação mensal",
    ],
    integrations: ["RD Station CRM", "HubSpot", "Pipedrive", "Kommo", "WhatsApp API oficial", "Formulários", "Planilhas"],
    pricing: {
      from: 5000,
      prefix: "Implantação a partir de",
      timeline: "2 a 3 semanas",
      details: [
        "Licença do CRM paga diretamente pela empresa.",
        "Combina com SDR com IA e Funis no pacote Máquina de Receita.",
      ],
    },
    security: "CRM contratado em nome da sua empresa, com permissões por usuário e adequação à LGPD.",
    indicators: ["Conversão por etapa do funil", "Ciclo médio de venda", "Orçamentos sem follow-up", "Previsão × receita realizada"],
    faq: [
      { q: "Qual CRM vocês recomendam?", a: "Depende do seu processo e do orçamento. Recomendamos no Diagnóstico; se você já tem um CRM, trabalhamos com ele." },
      { q: "Minha equipe vai conseguir usar?", a: "Incluímos treinamento e deixamos o CRM simples: o que puder ser automático, é." },
      { q: "Consigo migrar os dados da planilha?", a: "Sim. A migração e a limpeza dos dados fazem parte da implantação." },
      { q: "A licença do CRM está inclusa?", a: "Não. A licença é paga direto ao fornecedor, em nome da sua empresa — assim os dados são seus." },
    ],
    cta: { title: "Quantos orçamentos estão parados sem follow-up?", text: "Comece pelo Diagnóstico." },
    related: ["sdr-com-ia", "funis-automatizados"],
    guide: "agentes-de-ia-para-empresas",
    visual: "kanban",
    updatedAt: UPDATED,
  },
  {
    slug: "funis-automatizados",
    solution: "vendas-e-receita",
    name: "Funis & Nutrição Automatizada",
    cardDescription: "Sequências de e-mail e WhatsApp disparadas pelo comportamento de cada lead.",
    icon: "workflow",
    title: "Funis e Nutrição Automatizada para Empresas",
    metaDescription:
      "Sequências automáticas de e-mail e WhatsApp disparadas pelo comportamento de cada lead, até ele estar pronto para comprar. A partir de R$ 4.000.",
    h1: "Funis & Nutrição Automatizada: o follow-up que ninguém esquece",
    answer:
      "Criamos sequências automáticas de e-mail e WhatsApp que acompanham cada lead de acordo com o que ele faz — abriu, clicou, pediu orçamento, sumiu. O contato certo chega na hora certa, sem depender da memória do vendedor. Ideal para empresas com ciclo de venda de dias ou semanas e muitos leads que ainda não estão prontos.",
    forWho: [
      "Empresas com ciclo de venda de dias ou semanas.",
      "Negócios que geram muitos leads que ainda não estão prontos para comprar.",
      "Times comerciais que não conseguem acompanhar todo mundo.",
      "Quem envia orçamento e não sabe o que acontece depois.",
    ],
    steps: [
      { title: "Mapeamos a jornada", text: "Do primeiro contato à compra, com os pontos em que o lead esfria." },
      { title: "Escrevemos as mensagens", text: "Com você, no tom da marca, com conteúdo útil." },
      { title: "Configuramos os gatilhos", text: "Abriu, clicou, respondeu, sumiu: cada comportamento tem uma resposta." },
      { title: "A IA personaliza", text: "Cada mensagem usa o contexto do lead, não um texto genérico." },
      { title: "Lead aquecido vai para o vendedor", text: "Com alerta no CRM e o histórico completo." },
    ],
    included: [
      "Mapa da jornada de compra",
      "Copy das sequências",
      "Automação de e-mail e WhatsApp",
      "Gatilhos por comportamento",
      "Integração com o CRM",
      "Relatório de desempenho",
      "Sustentação mensal",
    ],
    integrations: ["RD Station Marketing", "Brevo", "Mailchimp", "WhatsApp API oficial", "HubSpot", "Pipedrive", "Formulários"],
    pricing: {
      from: 4000,
      prefix: "Implantação a partir de",
      timeline: "2 a 3 semanas",
      details: [
        "Mensagens de marketing no WhatsApp são pagas à Meta e exigem consentimento (opt-in).",
        "Ferramenta de e-mail paga pela empresa.",
      ],
    },
    security: "Envio só para quem consentiu, descadastro em toda mensagem e registro de consentimento conforme a LGPD.",
    indicators: ["Taxa de abertura e de resposta", "Leads que avançam de etapa", "Tempo até virar oportunidade", "Descadastros"],
    faq: [
      { q: "Vou incomodar os meus leads?", a: "Não, se feito do jeito certo: frequência controlada, conteúdo útil e opção de sair em toda mensagem." },
      { q: "Posso mandar WhatsApp para toda a minha base?", a: "Só para quem consentiu, seguindo as regras da Meta e da LGPD. Mensagens de marketing são pagas à Meta." },
      { q: "Quem escreve as mensagens?", a: "Nós, com você. Cada sequência é aprovada antes de ir ao ar." },
      { q: "Funciona sem CRM?", a: "Funciona com a ferramenta de e-mail, mas o ganho é bem maior integrado a um CRM." },
    ],
    cta: { title: "Quantos leads esfriam por falta de acompanhamento?", text: "Comece pelo Diagnóstico." },
    related: ["crm-e-pipeline", "reativacao-de-clientes"],
    guide: "agentes-de-ia-para-empresas",
    visual: "sequence",
    updatedAt: UPDATED,
  },
  {
    slug: "reativacao-de-clientes",
    solution: "vendas-e-receita",
    name: "Reativação de Clientes",
    cardDescription: "Campanhas que trazem de volta clientes parados e orçamentos perdidos.",
    icon: "refresh",
    title: "Reativação de Clientes com IA para Empresas",
    metaDescription:
      "Campanhas com IA que reengajam clientes inativos e orçamentos perdidos pelo WhatsApp, com conversa personalizada. A partir de R$ 4.500 por campanha.",
    h1: "Reativação de Clientes: a receita que já está na sua base",
    answer:
      "A Reativação de Clientes é uma campanha com IA que volta a conversar com clientes parados e orçamentos perdidos, de forma personalizada, pelo WhatsApp e por e-mail. O agente responde quem se interessa, qualifica e passa para o vendedor. É a forma mais rápida de gerar receita com IA, porque trabalha com contatos que já conhecem a sua empresa.",
    forWho: [
      "Empresas com base de clientes que não compram há meses.",
      "Negócios com muitos orçamentos enviados e não fechados.",
      "Serviços recorrentes (clínicas, escolas, oficinas) com clientes que sumiram.",
      "Quem quer um primeiro projeto de IA com retorno rápido.",
    ],
    steps: [
      { title: "Organizamos a base", text: "Higienização e segmentação por último contato, histórico e ticket." },
      { title: "Filtramos o consentimento", text: "Só entra na campanha quem pode receber mensagens." },
      { title: "Criamos a abordagem", text: "Por segmento, com um motivo real para voltar a conversar." },
      { title: "Disparo gradual", text: "E o agente de IA conversa com quem responde." },
      { title: "Oportunidades para o vendedor", text: "Com relatório da receita gerada pela campanha." },
    ],
    included: [
      "Higienização e segmentação da base",
      "Validação de consentimento",
      "Copy por segmento",
      "Disparo gradual pela API oficial",
      "Agente de IA para as respostas",
      "Integração com o CRM",
      "Relatório de resultado",
    ],
    integrations: ["WhatsApp API oficial", "E-mail", "RD Station", "HubSpot", "Pipedrive", "ERPs e sistemas de gestão", "Planilhas"],
    pricing: {
      from: 4500,
      prefix: "A partir de",
      suffix: "por campanha",
      timeline: "1 a 2 semanas",
      details: [
        "Mensagens de marketing pagas pela empresa, direto à Meta.",
        "Sujeito ao consentimento dos contatos (LGPD e regras do WhatsApp).",
      ],
    },
    security: "Somente contatos com consentimento, descadastro respeitado e dados tratados conforme a LGPD.",
    indicators: ["Contatos reativados", "Respostas por segmento", "Oportunidades geradas", "Receita atribuída à campanha"],
    faq: [
      { q: "Minha base é antiga. Ainda vale a pena?", a: "Geralmente sim — é justamente onde há receita parada. Começamos pela higienização para não desperdiçar mensagens." },
      { q: "Posso ser bloqueado no WhatsApp?", a: "O risco cai muito com API oficial, consentimento, disparo gradual e mensagem relevante. Não fazemos disparo em massa sem critério." },
      { q: "Quanto tempo para ver resultado?", a: "Como a base já conhece a sua empresa, as respostas começam nos primeiros dias da campanha." },
      { q: "E se o cliente não quiser mais contato?", a: "Registramos o descadastro e ele sai de todas as campanhas." },
    ],
    cta: { title: "Quanto vale a base de clientes que você não procura mais?", text: "Comece pelo Diagnóstico." },
    related: ["funis-automatizados", "sdr-com-ia"],
    guide: "ia-no-whatsapp",
    visual: "sequence",
    updatedAt: UPDATED,
  },

  // ───────────────────────── Operações & Processos ─────────────────────────
  {
    slug: "automacao-de-documentos",
    solution: "operacoes",
    name: "Automação de Documentos",
    cardDescription: "IA que lê, extrai, valida e lança dados de notas, contratos e PDFs.",
    icon: "file",
    featured: true,
    title: "Automação de Documentos com IA para Empresas",
    metaDescription:
      "IA que lê, extrai e organiza dados de notas, contratos e PDFs, e gera documentos a partir de modelos. Menos digitação, menos erro. Implantação a partir de R$ 12.000.",
    h1: "Automação de Documentos com IA: da leitura ao lançamento, sem digitar",
    answer:
      "A automação de documentos com IA lê notas fiscais, contratos, PDFs e formulários, extrai os dados, valida e lança nos seus sistemas, além de gerar documentos a partir de modelos. Elimina a digitação manual, reduz erros e libera horas da equipe. Ideal para contabilidades, escritórios de advocacia, clínicas e empresas que processam grandes volumes de documentos.",
    forWho: [
      "Equipes que digitam dados de dezenas ou centenas de documentos por mês.",
      "Escritórios e clínicas que geram contratos, peças e laudos repetitivos.",
      "Empresas com processos que dependem de conferência manual.",
    ],
    steps: [
      { title: "Mapeamos", text: "Os documentos e os dados que importam." },
      { title: "A IA lê e extrai", text: "As informações, mesmo de PDFs e imagens." },
      { title: "Valida", text: "Contra as suas regras de negócio." },
      { title: "Lança", text: "Nos sistemas, e gera os documentos de saída." },
      { title: "Fila de exceções", text: "Só o que foge ao padrão vai para revisão humana." },
    ],
    included: [
      "Modelagem dos documentos",
      "Extração com IA (PDF, imagem e digitalizados)",
      "Regras de validação",
      "Integração com os sistemas de destino",
      "Geração de documentos por modelos",
      "Fila de revisão humana",
      "Sustentação mensal",
    ],
    integrations: ["E-mail", "Google Drive", "ERPs", "Sistemas contábeis", "Sistemas jurídicos", "Planilhas", "Assinatura digital"],
    pricing: {
      from: 12000,
      prefix: "Implantação a partir de",
      timeline: "3 a 6 semanas, conforme volume e complexidade",
      details: [
        "Inclui sustentação mensal.",
        "Recomendamos IA Privada quando os documentos contêm dados sensíveis.",
      ],
    },
    security: "Processamento com controle de acesso e logs; opção de IA privada para documentos sensíveis; conformidade com a LGPD.",
    indicators: ["Documentos processados por mês", "% processados sem revisão humana", "Horas devolvidas à equipe", "Erros de lançamento"],
    demoCase: "extracao-notas-fiscais",
    faq: [
      { q: "Funciona com documentos escaneados?", a: "Sim, a IA lê PDFs e imagens (OCR + extração)." },
      { q: "E se a IA errar?", a: "Regras de validação e uma fila de revisão garantem que só o conferido é lançado." },
      { q: "Meus documentos ficam seguros?", a: "Sim. Para dados sensíveis usamos IA privada, sem que os dados saiam do seu ambiente." },
      { q: "Integra com o meu sistema?", a: "Integramos com os sistemas contábeis, jurídicos e ERPs mais usados." },
    ],
    cta: { title: "Quantas horas sua equipe gasta digitando?", text: "Comece pelo Diagnóstico." },
    related: ["integracao-de-sistemas", "ia-privada"],
    guide: "agentes-de-ia-para-empresas",
    visual: "document",
    updatedAt: UPDATED,
  },
  {
    slug: "agente-de-conhecimento",
    solution: "operacoes",
    name: "Agente de Conhecimento Interno",
    cardDescription: "O “ChatGPT da empresa”, treinado nos seus documentos e citando a fonte.",
    icon: "book",
    title: "Agente de Conhecimento Interno com IA para Empresas",
    metaDescription:
      "Um assistente de IA treinado nos manuais, processos e contratos da sua empresa, que responde à equipe citando a fonte. A partir de R$ 10.000.",
    h1: "Agente de Conhecimento Interno: a resposta certa, com a fonte, em segundos",
    answer:
      "O Agente de Conhecimento Interno é um assistente de IA treinado nos documentos da sua empresa — manuais, processos, políticas e contratos — que responde às perguntas da equipe em linguagem natural e sempre cita a fonte. Reduz o tempo de busca, acelera o treinamento de novos colaboradores e diminui a dependência de quem “sabe onde está”.",
    forWho: [
      "Empresas com conhecimento espalhado em pastas, PDFs e na cabeça de poucas pessoas.",
      "Equipes que perdem tempo procurando procedimento, cláusula ou política.",
      "Operações com rotatividade e treinamento constante.",
      "Escritórios e contabilidades com grande acervo.",
    ],
    steps: [
      { title: "Reunimos as fontes", text: "Drive, SharePoint, PDFs e wiki, com curadoria do que é oficial." },
      { title: "Indexamos o acervo", text: "Com RAG, respeitando as permissões de cada pessoa." },
      { title: "A equipe pergunta", text: "Pelo chat, pelo Slack, pelo Teams ou pelo WhatsApp interno." },
      { title: "Resposta com fonte", text: "O agente cita o documento e o trecho de onde tirou a resposta." },
      { title: "Base sempre atual", text: "Documento novo ou alterado entra na base automaticamente." },
    ],
    included: [
      "Curadoria das fontes",
      "Indexação do acervo (RAG)",
      "Controle de acesso por perfil",
      "Interface de chat (web, Slack ou Teams)",
      "Citação da fonte em toda resposta",
      "Atualização automática da base",
      "Logs de uso",
      "Sustentação mensal",
    ],
    integrations: ["Google Drive", "SharePoint", "OneDrive", "Notion", "Confluence", "PDFs", "Slack", "Microsoft Teams"],
    pricing: {
      from: 10000,
      prefix: "Implantação a partir de",
      timeline: "3 a 5 semanas",
      details: ["Inclui sustentação mensal.", "Recomendamos IA Privada quando o acervo contém dados sensíveis."],
    },
    security: "Respostas respeitam as permissões de cada usuário; provedores com não retenção de dados ou IA privada; logs de uso.",
    indicators: ["Tempo de busca por informação", "Perguntas respondidas por semana", "Tempo de integração de novos colaboradores", "Perguntas sem resposta (que viram documentação)"],
    demoCase: "conhecimento-interno-contabil",
    faq: [
      { q: "Ele pode inventar resposta?", a: "O agente responde a partir dos seus documentos e mostra a fonte. Quando não encontra, diz que não encontrou." },
      { q: "Todo mundo vê tudo?", a: "Não. Cada pessoa só recebe respostas de documentos que tem permissão para acessar." },
      { q: "Meus documentos vão treinar a IA de alguém?", a: "Não. Usamos provedores com não retenção de dados ou IA privada." },
      { q: "Como mantenho a base atualizada?", a: "A base se atualiza sozinha quando um documento é criado ou alterado nas fontes conectadas." },
    ],
    cta: { title: "Quanto tempo sua equipe perde procurando informação?", text: "Comece pelo Diagnóstico." },
    related: ["automacao-de-documentos", "ia-privada"],
    guide: "agentes-de-ia-para-empresas",
    visual: "knowledge",
    updatedAt: UPDATED,
  },
  {
    slug: "integracao-de-sistemas",
    solution: "operacoes",
    name: "Integração de Sistemas",
    cardDescription: "ERP, CRM, planilhas e sistemas legados conversando sozinhos.",
    icon: "plug",
    title: "Integração de Sistemas para Empresas",
    metaDescription:
      "Conectamos ERP, CRM, planilhas, APIs e sistemas legados para que os dados fluam sozinhos, sem retrabalho nem divergência. A partir de R$ 4.000.",
    h1: "Integração de Sistemas: o dado digitado uma vez, disponível em todo lugar",
    answer:
      "A Integração de Sistemas conecta ERP, CRM, planilhas, e-commerce, APIs e sistemas legados para que as informações fluam automaticamente entre eles. Acaba com a digitação dupla, com dados divergentes e com o “exporta, ajusta e importa”. Ideal para empresas que usam vários sistemas que não conversam entre si.",
    forWho: [
      "Empresas que digitam a mesma informação em dois ou mais sistemas.",
      "Operações com relatórios que não batem entre áreas.",
      "Negócios com e-commerce, ERP e CRM separados.",
      "Quem depende de um sistema antigo que ninguém quer tocar.",
    ],
    steps: [
      { title: "Mapeamos", text: "Sistemas, dados e onde está o retrabalho hoje." },
      { title: "Desenhamos o fluxo", text: "Origem, transformação, destino e regras de cada dado." },
      { title: "Construímos", text: "Via API, webhook, n8n ou código, conforme o caso." },
      { title: "Monitoramos", text: "Alerta de falha e reprocessamento automático." },
      { title: "Documentamos", text: "E mantemos com sustentação mensal." },
    ],
    included: [
      "Mapeamento de sistemas e dados",
      "Desenho dos fluxos de integração",
      "Desenvolvimento (API, webhook, n8n ou código)",
      "Tratamento de erros e alertas",
      "Logs de execução",
      "Documentação",
      "Sustentação mensal",
    ],
    integrations: ["Omie", "Bling", "Tiny", "TOTVS", "SAP (via API)", "RD Station", "HubSpot", "Shopify", "WooCommerce", "Google Sheets", "Bancos de dados"],
    pricing: {
      from: 4000,
      prefix: "Integrações intermediárias a partir de",
      timeline: "1 a 3 semanas",
      details: [
        "Integrações complexas (sistemas legados sem API, alto volume) são orçadas após o Diagnóstico.",
        "Inclui sustentação mensal.",
      ],
    },
    security: "Credenciais em cofre, contas em nome da sua empresa, logs de cada execução e tráfego criptografado.",
    indicators: ["Horas de digitação eliminadas", "Divergências de dados entre sistemas", "Tempo entre o evento e o dado disponível", "Falhas detectadas e reprocessadas"],
    demoCase: "integracao-pedidos-estoque",
    faq: [
      { q: "Meu sistema é antigo e não tem API. Dá para integrar?", a: "Muitas vezes, sim: via banco de dados, arquivos, e-mail ou automação de interface. Avaliamos a opção mais segura no Diagnóstico." },
      { q: "O que acontece se a integração falhar?", a: "Você recebe um alerta e a execução é reprocessada automaticamente quando o sistema volta." },
      { q: "Fico dependente de vocês?", a: "Não. Documentação, código e fluxos ficam em contas da sua empresa, com cláusula de saída." },
      { q: "Vocês usam n8n?", a: "Sim, quando faz sentido: é uma ferramenta robusta, com opção de hospedagem própria. Para casos específicos, escrevemos código." },
    ],
    cta: { title: "Quantos sistemas na sua empresa não conversam entre si?", text: "Comece pelo Diagnóstico." },
    related: ["automacao-de-processos", "automacao-de-documentos"],
    guide: "agentes-de-ia-para-empresas",
    visual: "flow",
    updatedAt: UPDATED,
  },
  {
    slug: "automacao-de-processos",
    solution: "operacoes",
    name: "Automação de Processos",
    cardDescription: "Fluxos sob medida para o seu processo, do simples ao agente operacional.",
    icon: "cog",
    title: "Automação de Processos Sob Medida com n8n e Agentes de IA",
    metaDescription:
      "Fluxos de automação sob medida em n8n e agentes operacionais com IA para o processo específico da sua empresa. A partir de R$ 4.000.",
    h1: "Automação de Processos: o seu processo, rodando sozinho, do jeito que ele é",
    answer:
      "Construímos fluxos de automação sob medida, em n8n e com agentes de IA, para o processo específico da sua empresa: aprovações, cobranças, onboarding, relatórios e ordens de serviço. Da automação intermediária ao agente operacional que decide e age. Ideal para processos repetitivos que hoje dependem de planilha, e-mail e memória.",
    forWho: [
      "Processos repetitivos que dependem de planilha, e-mail e memória.",
      "Relatórios montados à mão toda semana.",
      "Rotinas de cobrança, aprovação ou onboarding que atrasam.",
      "Empresas que já tentaram ferramentas prontas e não se adaptaram.",
    ],
    steps: [
      { title: "Mapeamos o processo", text: "Como ele é hoje, com tempos e custos de cada etapa." },
      { title: "Redesenhamos", text: "Eliminando as etapas que não agregam antes de automatizar." },
      { title: "Construímos", text: "A automação e os pontos de decisão da IA." },
      { title: "Validamos", text: "Com casos reais e uma fila de exceções." },
      { title: "Operamos", text: "Com monitoramento e melhorias contínuas." },
    ],
    included: [
      "Mapeamento do processo atual e do processo futuro",
      "Construção em n8n ou código",
      "Agentes de IA para os pontos de decisão",
      "Fila de exceções",
      "Alertas e logs",
      "Documentação",
      "Sustentação mensal",
    ],
    integrations: ["n8n", "Google Workspace", "Microsoft 365", "ERPs", "CRMs", "WhatsApp API oficial", "E-mail", "Planilhas", "APIs"],
    pricing: {
      from: 4000,
      prefix: "A partir de",
      timeline: "2 a 5 semanas, conforme o processo",
      details: ["Inclui sustentação mensal.", "Contas do n8n e dos provedores em nome da sua empresa."],
      tiers: [
        { name: "Automação intermediária", from: 4000, note: "Fluxos com regras claras e integrações entre sistemas." },
        { name: "Automação avançada (agente operacional)", from: 10000, note: "Agente de IA que interpreta, decide e age, com revisão humana." },
      ],
    },
    security: "Execução com logs, credenciais protegidas, contas em nome da sua empresa e fila de revisão para decisões sensíveis.",
    indicators: ["Horas por semana devolvidas à equipe", "Tempo de ciclo do processo", "Erros e retrabalho", "% de casos que vão para exceção"],
    demoCase: "relatorio-semanal-diretoria",
    faq: [
      { q: "Que processos dá para automatizar?", a: "Todo processo repetitivo, com regras claras e dados digitais, é candidato. Os que exigem julgamento ganham um agente de IA com revisão humana." },
      { q: "Qual a diferença entre automação intermediária e avançada?", a: "A intermediária segue regras fixas. A avançada usa um agente de IA para interpretar textos, documentos e situações e decidir o próximo passo." },
      { q: "Onde o n8n fica hospedado?", a: "Na nuvem do n8n ou em servidor da sua empresa. Nos dois casos, a conta é sua." },
      { q: "E se o processo mudar?", a: "A sustentação mensal inclui ajustes nos fluxos." },
    ],
    cta: { title: "Qual processo da sua empresa ainda depende de memória?", text: "Comece pelo Diagnóstico." },
    related: ["integracao-de-sistemas", "automacao-de-documentos"],
    guide: "agentes-de-ia-para-empresas",
    visual: "flow",
    updatedAt: UPDATED,
  },

  // ───────────────────────── IA Corporativa ─────────────────────────
  {
    slug: "ia-privada",
    solution: "ia-corporativa",
    name: "IA Privada",
    cardDescription: "Toda a inteligência, sem que os dados saiam do seu controle.",
    icon: "lock",
    featured: true,
    title: "IA Privada para Empresas | Dados que não saem do seu controle",
    metaDescription:
      "IA rodando em ambiente privado, sem expor os dados da sua empresa. Ideal para jurídico e saúde. Governança, LGPD e controle total. Projetos a partir de R$ 20.000.",
    h1: "IA Privada: toda a inteligência, nenhum vazamento de dados",
    answer:
      "IA privada é o uso de inteligência artificial em um ambiente controlado pela empresa, em que os dados não são usados para treinar modelos de terceiros nem saem do seu domínio. Permite aplicar IA a documentos, atendimento e análise mesmo com informações confidenciais. Ideal para escritórios de advocacia, clínicas e empresas que lidam com dados sensíveis e precisam cumprir a LGPD.",
    forWho: [
      "Escritórios de advocacia que querem usar IA em peças e pesquisa sem expor dados de clientes.",
      "Clínicas e empresas de saúde com dados de pacientes.",
      "Empresas que não podem enviar informações para APIs públicas.",
    ],
    paths: [
      {
        name: "IA em Nuvem Privada",
        text: "Modelos de ponta via provedor corporativo, com contrato de não retenção de dados. Atende à maioria dos casos regulados, com o melhor custo-benefício.",
        price: "A partir de R$ 20.000",
      },
      {
        name: "IA Dedicada / On-premise",
        text: "Modelo aberto rodando em servidor próprio ou dedicado, para quando a exigência é máxima.",
        price: "A partir de R$ 45.000 + infraestrutura (GPU)",
      },
    ],
    steps: [
      { title: "Avaliamos", text: "O nível de sensibilidade dos dados e a exigência regulatória." },
      { title: "Escolhemos o caminho", text: "Nuvem privada ou dedicada, junto com você." },
      { title: "Implantamos", text: "O ambiente com controle de acesso e registro de uso." },
      { title: "Conectamos", text: "A IA aos seus documentos e processos (RAG no seu acervo)." },
      { title: "Governança contínua", text: "Logs, auditoria e ajustes." },
    ],
    included: [
      "Arquitetura do ambiente privado",
      "Controle de acesso",
      "Logs e auditoria",
      "Conexão ao acervo interno (RAG)",
      "Política de uso",
      "Sustentação mensal",
    ],
    integrations: ["Microsoft Azure", "Google Cloud", "AWS", "Modelos abertos", "Google Drive", "SharePoint", "Sistemas jurídicos", "Prontuários eletrônicos"],
    pricing: {
      from: 20000,
      prefix: "A partir de",
      details: [
        "Inclui sustentação mensal.",
        "A infraestrutura de GPU, quando necessária, é repassada.",
      ],
      tiers: [
        { name: "Nuvem privada", from: 20000 },
        { name: "Dedicada / on-premise", from: 45000, note: "Mais a infraestrutura (GPU)." },
      ],
    },
    security: "É o núcleo desta solução: não retenção de dados, controle de acesso, logs e conformidade com a LGPD.",
    indicators: ["Tempo de pesquisa por demanda", "Reaproveitamento do acervo", "Adesão da equipe", "Acessos registrados e auditáveis"],
    demoCase: "assistente-juridico-ia-privada",
    faq: [
      { q: "Qual a diferença para usar o ChatGPT normal?", a: "Na IA privada, seus dados não treinam o modelo nem saem do seu controle." },
      { q: "Preciso de servidor próprio?", a: "Não necessariamente. A nuvem privada atende à maioria dos casos, com não retenção de dados." },
      { q: "Atende à LGPD?", a: "Sim, com governança, controle de acesso e registros para auditoria." },
      { q: "Serve para o meu acervo de documentos?", a: "Sim, conectamos a IA aos seus documentos com segurança." },
    ],
    cta: { title: "Quer usar IA sem abrir mão da confidencialidade?", text: "Comece pelo Diagnóstico." },
    related: ["governanca-ia-lgpd", "agente-de-conhecimento"],
    guide: "ia-e-lgpd",
    visual: "vault",
    updatedAt: UPDATED,
  },
  {
    slug: "governanca-ia-lgpd",
    solution: "ia-corporativa",
    name: "Governança & Segurança de IA",
    cardDescription: "Política de uso, riscos mapeados, controles e adequação à LGPD.",
    icon: "shield",
    title: "Governança de IA e LGPD para Empresas",
    metaDescription:
      "Política de uso de IA, mapeamento de riscos, adequação à LGPD, controles e logs para empresas que já usam IA. A partir de R$ 6.000.",
    h1: "Governança & Segurança de IA: regras claras, risco sob controle",
    answer:
      "A Governança de IA organiza como a sua empresa usa inteligência artificial: política de uso, mapeamento de riscos, adequação à LGPD, controles de acesso e registros para auditoria. É o ponto de partida ideal para empresas em que a equipe já usa IA de forma informal e a diretoria precisa de segurança para avançar.",
    forWho: [
      "Empresas em que colaboradores já usam ChatGPT e similares sem regra.",
      "Diretorias que querem adotar IA, mas precisam de controle.",
      "Setores regulados: jurídico, saúde e financeiro.",
      "Empresas que precisam demonstrar conformidade a clientes e parceiros.",
    ],
    steps: [
      { title: "Levantamos o uso atual", text: "Quais ferramentas, com quais dados e por quem." },
      { title: "Mapeamos os riscos", text: "Dados pessoais, confidencialidade e decisões automatizadas." },
      { title: "Escrevemos a política", text: "Regras de uso e fluxo de aprovação de novas ferramentas." },
      { title: "Implantamos controles", text: "Contas corporativas, acessos e registros de uso." },
      { title: "Treinamos e revisamos", text: "A equipe aprende as regras; revisamos periodicamente." },
    ],
    included: [
      "Inventário de uso de IA",
      "Matriz de riscos",
      "Política de uso de IA",
      "Adequação à LGPD dos fluxos com IA",
      "Controles de acesso e logs",
      "Treinamento da equipe",
      "Revisão periódica",
    ],
    integrations: ["Google Workspace", "Microsoft 365", "ChatGPT Enterprise / Team", "Claude for Work", "Gemini para empresas", "SSO corporativo"],
    pricing: {
      from: 6000,
      prefix: "A partir de",
      timeline: "3 a 4 semanas",
      details: [
        "Trabalhamos junto com o jurídico ou o DPO da sua empresa na parte legal.",
        "Também funciona como porta de entrada para projetos de IA privada.",
      ],
    },
    security: "Esta solução é a própria camada de segurança: política, controles, registros e treinamento.",
    indicators: ["Ferramentas de IA mapeadas e aprovadas", "Colaboradores treinados", "Usos fora da política identificados", "Pendências de adequação resolvidas"],
    faq: [
      { q: "Preciso de governança se ainda não uso IA oficialmente?", a: "Provavelmente a sua equipe já usa, só que sem controle. O primeiro passo é descobrir onde." },
      { q: "Vocês substituem o DPO ou o jurídico?", a: "Não. Trabalhamos junto com eles, cuidando da parte técnica e operacional." },
      { q: "Quanto tempo leva?", a: "De 3 a 4 semanas para o ciclo inicial, com revisões periódicas depois." },
      { q: "A política trava o uso de IA?", a: "O objetivo é o contrário: dar segurança para a equipe usar mais, com as ferramentas e os dados certos." },
    ],
    cta: { title: "Sua equipe já usa IA. Com quais regras?", text: "Comece pelo Diagnóstico." },
    related: ["ia-privada", "agente-de-conhecimento"],
    guide: "ia-e-lgpd",
    visual: "vault",
    updatedAt: UPDATED,
  },
];

export const getHub = (slug: string) => hubs.find((h) => h.slug === slug);
export const getService = (slug: string) => services.find((s) => s.slug === slug);
export const servicesOf = (hub: SolutionSlug) => services.filter((s) => s.solution === hub);
export const serviceHref = (s: Pick<ServicePage, "solution" | "slug">) => `/solucoes/${s.solution}/${s.slug}/`;
export const hubHref = (slug: SolutionSlug) => `/solucoes/${slug}/`;
